### ISSUE TITLE
Fix the flower quest

### ISSUE THREAD

**Issue by ChesterLuna** [Retro-Muffins/Arcadia#39]
Make the player just be able to pick up the number of flowers required.

(They didnt like that you could pick all of the flowers, then it didnt work)

**Comment by JTLee98** [comment]
DEADLINE Part 1 : DEC.05
- work out how to fix the design of the quest (@imanqur , @ChesterLuna )
DEADLINE - Part 2 : DEC.10
- fix the programming

**Comment by JTLee98** [comment]
also see: issue #40

**Comment by imanqur** [comment]
If player picks up the wrong flowers (or have extra in inventory that are not the ones asked for, etc.)
— note, also includes why the wrong flowers will disappear out of inventory


Craig: These are not!! The colours I asked for!!! I can’t have anything tainting the specific order of flowers I need for my beloved Hiku—
Craig: Agh!! Give these to me, these aren’t right! And try again, please!
He stomps out the flowers.
Craig: I want (fill in the flowers he’s currently requesting here)

**Comment by ChesterLuna** [comment]
The icons that I used for the items are:
red 53
blue 54
purple 55
yellow 56
green 57
