### ISSUE TITLE
doors triggered by player touch

### ISSUE THREAD

**Issue by triaksh25** [Retro-Muffins/Arcadia#42]
Some doors did not have an action button, but instead just work only when you walk into them. Whereas some of the doors just have an action button to go through them.

**Comment by JTLee98** [comment]
problem: some doors are triggered by player touch
fix: make all the event triggers for the doors to be `Action Button`
[see here](https://media.discordapp.net/attachments/1047213036286529626/1047316320099762216/Screenshot_2022-11-29_175831.png?width=368&height=501)

**Comment by JTLee98** [comment]
DEADLINE - DEC.03
