### ISSUE TITLE
Convert Lollypops

### ISSUE THREAD

**Issue by perig01** [Retro-Muffins/Arcadia#49]
It is unclear regarding the instructions for dipping the lollypops in the river.

**Comment by JTLee98** [comment]
quest needs to specify order to dip the lollipops

**Comment by ChesterLuna** [comment]
Actual: It tells the player to do the lollypop in an order.
Intended: Tell the player the flavours but not give an order

**Comment by JTLee98** [comment]
DEADLINE - DEC.03

**Comment by imanqur** [comment]
added candy options to make it more clear
