### ISSUE TITLE
Change Cecilia sprite to ghost sprite

### ISSUE THREAD

**Issue by ChesterLuna** [Retro-Muffins/Arcadia#55]
Cecilia sprite has normal color instead of the ghost color that we wanted, Im not sure if the sprite exists but if it does, just change it in the file.

**Comment by JTLee98** [comment]
spritesheet is located at: [`/img/characters/$Chad_Cecilia.png`](https://github.com/Retro-Muffins/Arcadia/blob/master/img/characters/%24Chad_Cecilia.png)

**Comment by JTLee98** [comment]
DEADLINE - DEC.01
