### ISSUE TITLE
Alex should walk over to some things before interacting with them

### ISSUE THREAD

**Issue by JTLee98** [Retro-Muffins/Arcadia#61]
currently, we can interact with all events with clicking, even if alex is located far away.
for certain interactions, we want to make alex walk over to them before interacting.

fix: @ChesterLuna knows how

**Comment by JTLee98** [comment]
we are going to do this after finishing all other issues

**Comment by ChesterLuna** [comment]
Plugin Commands:

Move the player near the event (1 tile around it):
SMARTPATH eventId RM_MOVE_NEAR		#normally just use 0
SMARTPATH eventId RM_MOVE x y			#eventId is not necessary, just leave it as 0



event = number for specific event
event = 0 for "this" event
event = $gameVariables.value(x) to get the event id from variable x
