### ISSUE TITLE
Re-design the keys merge in the rager

### ISSUE THREAD

**Issue by ChesterLuna** [Retro-Muffins/Arcadia#66]
Right now we have 4 stands to add the keys and it merges into the central one.

We were given feedback in the vertical slice that we should change it into something that would make more sense diegetically.
Either a workbench. (which needs art and coding)
Or adding a visual cue that the 4 pillars are conected. (Like a line in the floor)

**Comment by perig01** [comment]
i did 2 versions coloured and gray u can choose which is better
